[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.0"

remappings = [
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
